<!DOCTYPE html>
<html>
    <head>
        <title>Hai cantik nya ihsan</title>
    </head>
    <body>
    <script>
        alert("Halo cantik ny ak");
        alert("Baru bangun yaa");
        alert("Pasti lgi mikirin ak yaa");
        alert("Hehehe");
        alert("Ak minta maaf ya yg kemaren");
        alert("Maapin ya cantik");;
        alert("Kmu udh mkn gk")
        alert("Yaudh klo blum sana makan")
        alert("Makan gk")
        alert("Tpi makan ny jngn yg manis manis ya")
        alert("Karna manisnya ad di kmu")
        alert("Anjrooott haahaha")
        alert("Ciee senyum senyum")
        alert("Kok muka kamu manis bnget si")
        alert("Hahaha")
        alert("Yaudh makan ya")
        alert("Dadahhhh cntik")
        alert("Iiiii love youu")
        alert("(Ihsan)")
        
    </script>
    </body>
</html>
